### ISSUE TITLE
Actividad 1 Mapa Mental 

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Daniel-Velasco-Lopez#1]
Daniel Velasco López
Mapa Mental actividad 1

![Mapa Mental-1](https://user-images.githubusercontent.com/112217987/187792264-918891a1-760c-4db5-9b60-b4fb4b5bf08d.png)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 1 MAPA MENTAL
DE 20% DE LA ACTIVIDAD OBTUVISTE 17.2% DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
